### PR TITLE
Add changes to the Public folder/main.js

### PR DESCRIPTION
**Pull request by JuanPabloNSZ**
Hello! 😊
- I modified the main.js file (public folder), to be able to connect those functions with the messages.js (controllers folder).
- I also did a minor changes in the messages.js (controllers folder): markLiked, markUnliked, deleteMessage.
- Finally, and **only to test those buttons**, I added a little section in the messages.ejs (views folder).

Please, let me know what you think and feel free to test this branch before we can merge it.

### CODE REVIEW

**Review by emtek995 — COMMENTED** [review]
It is generally bad practice to use hard tabs to format code. It is also expected to work with the way the code is already formatted. When you change the formatting it makes the code review very difficult as it appears as the entire file has changed and it is hard to pick out the actual changes.

**Comment by JuanPabloNSZ** [comment]
> It is generally bad practice to use hard tabs to format code. It is also expected to work with the way the code is already formatted. When you change the formatting it makes the code review very difficult as it appears as the entire file has changed and it is hard to pick out the actual changes.

@emtek995 thank you, I didn't noticed it. I use the 'Prettier' extension which does the formatting automatically. I think I'll create a new branch and do a pull request from there.

**Review by emtek995 — CHANGES_REQUESTED** [review]
The changes in controllers/messages.js are not needed. The client side main.js does the reload after if gets the response from the controller.

**Comment by emtek995** [comment]
Thank you for fixing the formatting. I think this is a good lesson for a team to agree on formatting ahead of time and maybe create a prettier config file in the project so all formatting stays consistant.

**Comment by JuanPabloNSZ** [comment]
> The changes in controllers/messages.js are not needed. The client side main.js does the reload after if gets the response from the controller.

You are right. I did the changes now, deleting the line "res.redirect('/messages')" from controllers/messages.js

**Pull request merged**
